version: "3.9"

services:
  db:
    image: postgres:16
    container_name: expense-db
    environment:
      POSTGRES_DB: expense
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: expense-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: expense
      DB_USER: postgres
      DB_PASS: 123456

volumes:
  postgres_data:
